plugins {
    id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
    id 'maven-publish'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

version = "${project.mod_version}+MC${project.minecraft_version}"
group = project.maven_group

repositories {
    maven { url = "https://maven.bawnorton.com/releases" }
    mavenCentral()
    maven { url 'https://jitpack.io' }
}


dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    modImplementation('com.github.contariaa:atum:fe1f979836') {
        transitive = false
    }
    modImplementation('com.github.contariaa:SpeedrunAPI:96811e85e8')

//    modImplementation(
    modCompileOnly(
            'com.github.contariaa:seedqueue:62d3c7b4dc') {
        transitive = false
    }

    modCompileOnly("com.github.RedLime:SpeedRunIGT:f742cbaf81")
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

loom {
    decompilerOptions.named("vineflower") {
        options.put("mark-corresponding-synthetics", "1") // Adds names to lambdas - useful for mixins
    }
}

jar {
    inputs.property "archivesName", project.base.archivesName

    from("LICENSE") {
        rename { "${it}_${inputs.properties.archivesName}"}
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
    repositories {
    }
}